### ISSUE TITLE
task_interface_obj.evaluate_patches() opt_obj = None causing error

### ISSUE THREAD

**Issue by MerliN-47** [retis-ai/PatchAttackTool#3]
I am trying to run 2dod task on frcnn. I keep getting the following error
```python
Traceback (most recent call last):
  File "eval_script.py", line 88, in <module>
    optimize_patches(cfg)
  File "eval_script.py", line 62, in optimize_patches
    task_interface_obj.evaluate_patches()
  File "E:\Adversarial resources\PatchAttackTool\task_interfaces\OD_interface.py", line 278, in evaluate_patches
    patch_utils.save_images_list([ex_clear_image, true_label, ex_clear_out], self.train_loader, task='2dod', path=os.path.join(self.cfg["adv_patch"]["path"]["out_dir"], self.cfg["adv_patch"]["path"]["exp_name"]))
  File "E:\Adversarial resources\PatchAttackTool\patch_utils.py", line 1151, in save_images_list
    rgb = rgb[0].detach().cpu().numpy()
TypeError: 'NoneType' object is not subscriptable
``` 
I traced it back to task_interfac opt_obj being None and it stays None. Cant understand. Please help .Thank you !!

UPDATE - Further, this is caused because the NPS file mentioned in '/data01/f.nesti/SemanticSegmentation/printable_colors.txt' is missing. Please take a look.

**Comment by nsat-107** [comment]
@MerliN-47 did you find any workaround?

**Comment by QiTianyu-0403** [comment]
> I am trying to run 2dod task on frcnn. I keep getting the following error
> 
> Traceback (most recent call last):
>   File "eval_script.py", line 88, in <module>
>     optimize_patches(cfg)
>   File "eval_script.py", line 62, in optimize_patches
>     task_interface_obj.evaluate_patches()
>   File "E:\Adversarial resources\PatchAttackTool\task_interfaces\OD_interface.py", line 278, in evaluate_patches
>     patch_utils.save_images_list([ex_clear_image, true_label, ex_clear_out], self.train_loader, task='2dod', path=os.path.join(self.cfg["adv_patch"]["path"]["out_dir"], self.cfg["adv_patch"]["path"]["exp_name"]))
>   File "E:\Adversarial resources\PatchAttackTool\patch_utils.py", line 1151, in save_images_list
>     rgb = rgb[0].detach().cpu().numpy()
> TypeError: 'NoneType' object is not subscriptable
> I traced it back to task_interfac opt_obj being None and it stays None. Cant understand. Please help .Thank you !!
> 
> UPDATE - Further, this is caused because the NPS file mentioned in '/data01/f.nesti/SemanticSegmentation/printable_colors.txt' is missing. Please take a look.

Hello, I have also encountered a similar issue here. May I ask if the file '/data01/f.nesti/SemanticSegmentation/printable_colors.txt' is now available?
